sudo: false
language: node_js
node_js:
  - 10
  - 11
cache: npm
os:
  - windows
  - linux
  - osx
before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6'; fi